"""Generate a complete Skyrim LE creature behavior project from Oblivion data.

Emits per creature (all via packfile XML → hkxcmd, layouts copied from the
vanilla deer project dumps):

  actors/tes4/<name>/<name>project.hkx          (hkbProjectData boilerplate)
  actors/tes4/<name>/characters/<name>character.hkx  (hkbCharacterData: rig +
                                                 animation list + controller)
  actors/tes4/<name>/behaviors/<name>behavior.hkx    (GENERATED state machine)
  actors/tes4/<name>/character assets/skeleton.hkx   (from hkx_skeleton)
  actors/tes4/<name>/animations/*.hkx                (from hkx_anim)
  actors/tes4/<name>/motion_data.json                (root motion per clip —
                                                 consumed by the future
                                                 animationdata emitter)

v1 graph: one root hkbStateMachine — Idle (start, looping) + locomotion states
(forward/backward/turns/swim, looping) + one single-play state per attack /
recoil / stagger clip, entered by the standard engine events (wildcard
transitions) and exited by clip-end triggers (attackStop etc. → Idle). This is
the Oblivion animation-selection convention expressed as a graph; ragdoll
death, foot IK, look-at, and speed-blended gaits are later refinements
(vanilla wrapper-graph features).

Event names follow the vanilla creature vocabulary (quadrupedbehavior.hkx),
so RACE ATKD/ATKE records generated by tes5_import must use the same
`attackStart_TES4_<clip>` strings (build_attack_events()).
"""

import json
import os
import re
import sys

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _REPO)

from asset_convert.hkx_xml import HkxPackfile, compile_hkx  # noqa: E402

# hkxcmd emits these signatures for hk_2010; needed by our emitter
from asset_convert import hkx_xml  # noqa: E402
hkx_xml.SIGNATURES.update({
    'hkbBehaviorGraph': '0xb1218f86',
    'hkbBehaviorGraphData': '0x95aca5d',
    'hkbBehaviorGraphStringData': '0xc713064e',
    'hkbStateMachine': '0x816c1dcb',
    'hkbStateMachineStateInfo': '0xed7f9d0',
    'hkbStateMachineTransitionInfoArray': '0xe397b11e',
    'hkbClipGenerator': '0x333b85b9',
    'hkbClipTriggerArray': '0x59c23a0f',
    'hkbBlendingTransitionEffect': '0xfd8584fe',
    'hkbVariableValueSet': '0x27812d8d',
    'hkbVariableBindingSet': '0x338ad4ff',
    'hkbModifierGenerator': '0x1f81fae6',
    'hkbModifierList': '0xa4180ca1',
    'BSSpeedSamplerModifier': '0xd297fda9',
    'hkbCharacterData': '0x300d6808',
    'hkbCharacterStringData': '0x655b42bc',
    'hkbMirroredSkeletonInfo': '0xc6c2da4f',
    'hkbEventDrivenModifier': '0x7ed3f44e',
    'hkbEvaluateExpressionModifier': '0xf900f6be',
    'hkbExpressionDataArray': '0x4b9ee1a2',
    'hkbBlenderGenerator': '0x22df7147',
    'hkbBlenderGeneratorChild': '0xe2b384b0',
    'hkbPoweredRagdollControlsModifier': '0x7cb54065',
    'BSRagdollContactListenerModifier': '0x8003d8ce',
    'hkbKeyframeBonesModifier': '0x95f66629',
    'hkbRigidBodyRagdollControlsModifier': '0xaa87d1eb',
    'hkbBoneIndexArray': '0xaa8619',
    'hkbBoneWeightArray': '0xcd902b77',
    'BSIsActiveModifier': '0xb0fde45a',
    'hkbStateMachineEventPropertyArray': '0xb07b4388',
})


# ---------------------------------------------------------------------------
# Clip classification (the Oblivion filename convention)
# ---------------------------------------------------------------------------

LOCOMOTION_STATES = {
    # state name -> (kf basenames in priority order, enter event, exit event)
    'MoveForward': (['forward', 'runforward', 'fastforward'],
                    'moveStart', 'moveStop'),
    'MoveBackward': (['backward'], 'moveBackward', 'moveStop'),
    'TurnLeft': (['turnleft'], 'turnLeft', 'turnStop'),
    'TurnRight': (['turnright'], 'turnRight', 'turnStop'),
    'Swim': (['swimforward'], 'swimStart', 'swimStop'),
}
IDLE_CANDIDATES = ['idle']
# single-play interrupt states: clip fires returnToDefault at its end
# (vanilla-verbatim; the transition back is the root's returnToDefault
# global wildcard) and the STATE notifies its stop event on exit so the
# engine's combat/stagger controllers see completion.
SINGLE_PLAY = {
    'Recoil': (['recoil'], 'recoilStart', 'recoilStop'),
    'Stagger': (['stagger'], 'staggerStart', 'staggerStop'),
    # no exit notify/end trigger: the clip holds its last pose (dead on the
    # ground); ragdoll death is handled by the outer wrapper SM
    'Death': (['death', 'dies'], 'deathStart', None),
}

# Weapon draw/sheathe. The engine moves a weapon from its sheath node
# (Prn=WeaponMace etc.) into the hand (WEAPON) as part of playing the EQUIP
# animation — it is the graph, not the record, that arms an actor. Vanilla
# proves the point: the weapon-using creature graphs carry equip states and
# iRightHandType (draugrbehavior 436KB, falmerbehavior 276KB), while the
# bare-handed ones do not (wolfbehavior 7KB, chaurusbehavior 98KB). Our
# generated graph had weaponDraw/weaponSheathe EVENTS but no equip STATE, so
# nothing ever reparented the weapon: it stayed on the sheath node — or, before
# those nodes existed, on the actor root, sliding around at the creature's feet.
#
# Oblivion ships the source clips per weapon class (goblin: onehandequip,
# bowequip, staffequip, handtohandequip + unequip pairs), and ck-cmd's TES4
# analyzer catalogues exactly these names (ConvertNif.cpp:6054-6180), so the
# mapping is authored data rather than a guess.
#
# 'hand type' is the iRightHandType value the engine sets for that weapon class
# (from the vanilla behavior expressions: 7 = bow/ranged is called out
# explicitly in falmerbehavior's bAllowRotation guard, 0 = empty/hand-to-hand).
EQUIP_STANCES = {
    # state suffix -> (equip kf names, unequip kf names, hand types)
    'H2H':   (['handtohandequip', 'equip'],
              ['handtohandunequip', 'unequip'], (0,)),
    'OneH':  (['onehandequip'], ['onehandunequip'], (1, 2, 3, 4)),
    'TwoH':  (['twohandequip'], ['twohandunequip'], (5, 6)),
    'Bow':   (['bowequip'], ['bowunequip'], (7,)),
    'Staff': (['staffequip'], ['staffunequip'], (8,)),
}


def classify_clips(creature_dir: str) -> dict:
    """Scan an Oblivion creature folder into the v1 graph's clip roles.

    Returns {'idle': path, 'locomotion': {state: path}, 'attacks': [paths],
             'single': {state: path}, 'extra': [paths]}.
    """
    kfs = {}
    for fn in os.listdir(creature_dir):
        if fn.lower().endswith('.kf'):
            kfs[os.path.splitext(fn)[0].lower()] = os.path.join(
                creature_dir, fn)

    out = {'idle': None, 'locomotion': {}, 'attacks': [], 'single': {},
           'extra': [], 'run': None, 'equip': {}}
    used = set()
    for cand in IDLE_CANDIDATES:
        if cand in kfs:
            out['idle'] = kfs[cand]
            used.add(cand)
            break
    for state, (names, _e, _x) in LOCOMOTION_STATES.items():
        for n in names:
            if n in kfs:
                out['locomotion'][state] = kfs[n]
                used.add(n)
                break
    # run gait: a faster forward clip distinct from the walk clip — feeds the
    # MoveForward parametric speed blend (vanilla ForwardWalkBlend layout)
    if 'forward' in used:
        for n in ('runforward', 'fastforward'):
            if n in kfs and n not in used:
                out['run'] = kfs[n]
                used.add(n)
                break
    for state, (names, _e, _x) in SINGLE_PLAY.items():
        for n in names:
            if n in kfs:
                out['single'][state] = kfs[n]
                used.add(n)
                break
    # Weapon draw/sheathe clips, per weapon class (see EQUIP_STANCES). Claimed
    # BEFORE the attack sweep below: 'handtohandattackequip' contains 'attack'
    # and would otherwise be mistaken for an attack clip.
    for stance, (eq_names, uneq_names, _types) in EQUIP_STANCES.items():
        eq = next((kfs[n] for n in eq_names if n in kfs and n not in used),
                  None)
        if eq is None:
            continue
        uneq = next((kfs[n] for n in uneq_names if n in kfs and n not in used),
                    None)
        out['equip'][stance] = (eq, uneq)
        used.add(os.path.splitext(os.path.basename(eq))[0].lower())
        if uneq:
            used.add(os.path.splitext(os.path.basename(uneq))[0].lower())

    for name, path in kfs.items():
        if name in used:
            continue
        if 'attack' in name:
            out['attacks'].append(path)
        else:
            out['extra'].append(path)
    out['attacks'].sort()
    return out


def _clip_state_name(kf_path: str) -> str:
    base = os.path.splitext(os.path.basename(kf_path))[0]
    return re.sub(r'[^A-Za-z0-9]', '', base)


def build_attack_events(clips: dict) -> list:
    """attackStart event names, shared verbatim with RACE ATKE generation."""
    return [f'attackStart_TES4_{_clip_state_name(p)}'
            for p in clips['attacks']]


def state_defs(clips: dict) -> list:
    """The graph's clip-generator list, shared by the behavior XML and the
    animationdata manifest: (state_name, kf_path, looping, enter_evt,
    end_evt) tuples, Idle first.

    end_evt is the clip-END trigger registered in both the graph and the
    animationdata cache.  Single-play clips fire `returnToDefault` (vanilla
    convention — the root SM's global wildcard routes it back to
    DefaultState); the completion events the ENGINE listens for (attackStop/
    recoilStop/staggerStop) are state exitNotify events, not clip triggers.

    CombatStance is the looping combat-idle clip nested under the standing
    idle switch (combatStanceStart/Stop local transitions, routed from the
    engine's ActionDraw).  The weaponDraw reply the combat controller waits
    for is sent by the root-level StartCombat/StopCombat expression-modifier
    pair (vanilla quadruped layout), not by a state."""
    defs = []
    if clips['idle']:
        defs.append(('Idle', clips['idle'], True, None, None))
    for st, (_names, enter, _exit) in LOCOMOTION_STATES.items():
        if st in clips['locomotion']:
            defs.append((st, clips['locomotion'][st], True, enter, None))
    if clips['idle']:
        defs.append(('CombatStance', clips['idle'], True,
                     'combatStanceStart', None))
    for st, (_names, enter, _stop) in SINGLE_PLAY.items():
        if st in clips['single']:
            defs.append((st, clips['single'][st], False, enter,
                         'returnToDefault' if st != 'Death' else None))
    for kf, evt in zip(clips['attacks'], build_attack_events(clips)):
        defs.append((f'Attack_{_clip_state_name(kf)}', kf, False, evt,
                     'returnToDefault'))
    # Equip/unequip: single-play, entered on the engine's weaponDraw/
    # weaponSheathe. The clip END fires the reply the combat controller waits
    # for (weaponDraw once armed / weaponSheathe once stowed) so the actor is
    # cleared to attack; see EQUIP_STANCES.
    for stance, (eq, uneq) in sorted(clips.get('equip', {}).items()):
        defs.append((f'Equip_{stance}', eq, False,
                     f'equipStart_{stance}', 'weaponDraw'))
        if uneq:
            defs.append((f'Unequip_{stance}', uneq, False,
                         f'unequipStart_{stance}', 'weaponSheathe'))
    return defs


def speed_blend_plan(clips: dict, speeds: dict) -> list:
    """Children of the MoveForward parametric speed blend:
    [(clip_gen_name, kf_path, playback_rate, anchor u/s)], anchors strictly
    increasing.  None when the walk clip has no usable root-motion speed.

    Vanilla covers the whole commanded-speed range by re-anchoring the SAME
    clips at scaled playbackSpeeds (ForwardWalkBlend_Dog: walk@0.067→5 u/s,
    walk@1.0→74.54, walk@1.4→104.4, trot@0.65/1.0/1.5→186.8/287.3/425 —
    anchor == natural clip speed × rate).  A blend with only rate-1.0
    anchors plays wrong-rate animation at every other commanded speed and
    the actor glides/moonwalks (the 2026-07-16 gliding report).
    """
    fwd = clips['locomotion'].get('MoveForward')
    walk = speeds.get('walk')
    if not fwd or not walk:
        return None
    run_kf, run = clips.get('run'), speeds.get('run')
    # top children at 2.0× give the blend headroom up to twice the natural
    # gait speed — the MOVT command side (creature_races._movt_sped) raises
    # slow clips toward the Oblivion attribute-formula speed and caps at
    # this top anchor, so the animation rate always tracks ground speed.
    entries = [('MoveForwardSlow', fwd, 0.067), ('MoveForward', fwd, 1.0)]
    if run_kf and run and run > walk * 1.05:
        if 1.4 * walk < 0.75 * run:
            entries.append(('MoveForwardFast', fwd, 1.4))
        entries += [('MoveForwardRunSlow', run_kf, 0.75),
                    ('MoveForwardRun', run_kf, 1.0),
                    ('MoveForwardRunFast', run_kf, 1.5),
                    ('MoveForwardRunFaster', run_kf, 2.0)]
        natural = {id(fwd): walk, id(run_kf): run}
    else:
        entries += [('MoveForwardFast', fwd, 1.4),
                    ('MoveForwardFaster', fwd, 2.0)]
        natural = {id(fwd): walk}
    plan, last = [], 0.0
    for nm, kf, rate in entries:
        anchor = natural[id(kf)] * rate
        if anchor <= last * 1.01:
            continue
        plan.append((nm, kf, rate, anchor))
        last = anchor
    return plan if len(plan) >= 2 else None


def backward_blend_plan(clips: dict, speeds: dict) -> list:
    """Same treatment for MoveBackward (AI backpedals slowly)."""
    back = clips['locomotion'].get('MoveBackward')
    spd = speeds.get('back')
    if not back or not spd:
        return None
    return [('MoveBackwardSlow', back, 0.067, spd * 0.067),
            ('MoveBackward', back, 1.0, spd)]


# ---------------------------------------------------------------------------
# XML builders
# ---------------------------------------------------------------------------

def build_project_xml(character_file: str) -> str:
    pf = HkxPackfile(first_id=9)
    sd = pf.add('hkbProjectStringData')
    pd = pf.add('hkbProjectData')
    top = pf.add('hkRootLevelContainer')

    sd.param_array('animationFilenames', [])
    sd.param_array('behaviorFilenames', [])
    sd.param_strings('characterFilenames', [character_file])
    sd.param_array('eventNames', [])
    sd.param('animationPath', '')
    sd.param('behaviorPath', '')
    sd.param('characterPath', '')
    sd.param('fullPathToSource', '')

    pd.param('worldUpWS', '(0.000000 0.000000 1.000000 0.000000)')
    pd.param('stringData', sd.ref)
    pd.param('defaultEventMode', 'EVENT_MODE_IGNORE_FROM_GENERATOR')

    top.param_structs('namedVariants', [
        [('name', 'hkbProjectData'), ('className', 'hkbProjectData'),
         ('variant', pd.ref)]])
    return pf.render(top)


def build_character_xml(name: str, anim_files: list, behavior_file: str,
                        n_bones: int, capsule_height: float = 1.7,
                        capsule_radius: float = 0.4) -> str:
    pf = HkxPackfile(first_id=27)
    mirror = pf.add('hkbMirroredSkeletonInfo')
    strings = pf.add('hkbCharacterStringData')
    values = pf.add('hkbVariableValueSet')
    cdata = pf.add('hkbCharacterData')
    top = pf.add('hkRootLevelContainer')

    mirror.param('mirrorAxis', '(1.000000 0.000000 0.000000 0.000000)')
    mirror.param_array('bonePairMap', list(range(n_bones)))

    # Ragdoll-driver feedback config (vanilla dog character, verbatim): the
    # engine reads these character properties to couple the MODEL to the
    # RAGDOLL (worldFromModel feedback while ragdolled / hit-reacting).
    # Without them every gain defaults to 0 — the actor never follows its
    # ragdoll.  Values are IEEE-754 bit patterns in wordVariableValues:
    # 0.6 / 0.25 / 0.4 / 0.25.
    _DRIVER_PROPS = [
        ('m_worldFromModelFeedbackGain', 1058642330),   # 0.6
        ('m_alignWorldFromModelGain', 1048576000),      # 0.25
        ('m_errorUpDownBias', 1053609165),              # 0.4
        ('m_ankleOrientationGain', 1048576000),         # 0.25
    ]

    strings.param_array('deformableSkinNames', [])
    strings.param_array('rigidSkinNames', [])
    strings.param_strings('animationNames', anim_files)
    strings.param_array('animationFilenames', [])
    strings.param_strings('characterPropertyNames',
                          [n for n, _v in _DRIVER_PROPS])
    strings.param_array('retargetingSkeletonMapperFilenames', [])
    strings.param_array('lodNames', [])
    strings.param_array('mirroredSyncPointSubstringsA', [])
    strings.param_array('mirroredSyncPointSubstringsB', [])
    strings.param('name', name)
    strings.param('rigName', 'Character Assets\\skeleton.HKX')
    strings.param('ragdollName', 'Character Assets\\skeleton.HKX')
    strings.param('behaviorFilename', behavior_file)

    values.param_structs('wordVariableValues',
                         [[('value', v)] for _n, v in _DRIVER_PROPS])
    values.param_array('quadVariableValues', [])
    values.param_array('variantVariableValues', [])

    cdata.param_raw('characterControllerInfo', (
        '<hkobject>\n'
        f'\t<hkparam name="capsuleHeight">{capsule_height:.6f}</hkparam>\n'
        f'\t<hkparam name="capsuleRadius">{capsule_radius:.6f}</hkparam>\n'
        '\t<hkparam name="collisionFilterInfo">1</hkparam>\n'
        '\t<hkparam name="characterControllerCinfo">null</hkparam>\n'
        '</hkobject>'))
    cdata.param('modelUpMS', '(0.000000 0.000000 1.000000 0.000000)')
    cdata.param('modelForwardMS', '(0.000000 1.000000 0.000000 0.000000)')
    cdata.param('modelRightMS', '(1.000000 -0.000000 -0.000000 0.000000)')
    cdata.param_raw('characterPropertyInfos', '\n'.join(
        '<hkobject>\n'
        '\t<hkparam name="role">\n'
        '\t\t<hkobject>\n'
        '\t\t\t<hkparam name="role">ROLE_DEFAULT</hkparam>\n'
        '\t\t\t<hkparam name="flags">0</hkparam>\n'
        '\t\t</hkobject>\n'
        '\t</hkparam>\n'
        '\t<hkparam name="type">VARIABLE_TYPE_REAL</hkparam>\n'
        '</hkobject>' for _p in _DRIVER_PROPS),
        numelements=len(_DRIVER_PROPS))
    cdata.param_array('numBonesPerLod', [])
    cdata.param('characterPropertyValues', values.ref)
    cdata.param('footIkDriverInfo', 'null')
    cdata.param('handIkDriverInfo', 'null')
    cdata.param('stringData', strings.ref)
    cdata.param('mirroredSkeletonInfo', mirror.ref)
    cdata.param('scale', '1.000000')

    top.param_structs('namedVariants', [
        [('name', 'hkbCharacterData'), ('className', 'hkbCharacterData'),
         ('variant', cdata.ref)]])
    return pf.render(top)


_TRANSITION_TMPL = '''<hkobject>
\t<hkparam name="triggerInterval">
\t\t<hkobject>
\t\t\t<hkparam name="enterEventId">-1</hkparam>
\t\t\t<hkparam name="exitEventId">-1</hkparam>
\t\t\t<hkparam name="enterTime">0.000000</hkparam>
\t\t\t<hkparam name="exitTime">0.000000</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="initiateInterval">
\t\t<hkobject>
\t\t\t<hkparam name="enterEventId">-1</hkparam>
\t\t\t<hkparam name="exitEventId">-1</hkparam>
\t\t\t<hkparam name="enterTime">0.000000</hkparam>
\t\t\t<hkparam name="exitTime">0.000000</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="transition">{effect}</hkparam>
\t<hkparam name="condition">null</hkparam>
\t<hkparam name="eventId">{event_id}</hkparam>
\t<hkparam name="toStateId">{to_state}</hkparam>
\t<hkparam name="fromNestedStateId">0</hkparam>
\t<hkparam name="toNestedStateId">0</hkparam>
\t<hkparam name="priority">0</hkparam>
\t<hkparam name="flags">{flags}</hkparam>
</hkobject>'''

# vanilla transition flag sets: state-local transitions are plain
# FLAG_DISABLE_CONDITION; wildcard entries add FLAG_IS_LOCAL_WILDCARD;
# returnToDefault/deathStart are additionally global (bubble out of nested
# state machines).
_F_LOCAL = 'FLAG_DISABLE_CONDITION'
_F_WILD = 'FLAG_IS_LOCAL_WILDCARD|FLAG_DISABLE_CONDITION'

# vanilla dogbehavior #0125 hkbRigidBodyRagdollControlsModifier controlData,
# verbatim (shared by the root state's live tracker and the
# AnimateToRagdoll death stage)
_RB_RAGDOLL_CONTROL_DATA = (
    '<hkobject>\n'
    '\t<hkparam name="keyFrameHierarchyControlData">\n'
    '\t\t<hkobject>\n'
    '\t\t\t<hkparam name="hierarchyGain">0.170000</hkparam>\n'
    '\t\t\t<hkparam name="velocityDamping">0.000000</hkparam>\n'
    '\t\t\t<hkparam name="accelerationGain">1.000000</hkparam>\n'
    '\t\t\t<hkparam name="velocityGain">0.600000</hkparam>\n'
    '\t\t\t<hkparam name="positionGain">0.050000</hkparam>\n'
    '\t\t\t<hkparam name="positionMaxLinearVelocity">1.400000</hkparam>\n'
    '\t\t\t<hkparam name="positionMaxAngularVelocity">1.800000</hkparam>\n'
    '\t\t\t<hkparam name="snapGain">0.100000</hkparam>\n'
    '\t\t\t<hkparam name="snapMaxLinearVelocity">0.300000</hkparam>\n'
    '\t\t\t<hkparam name="snapMaxAngularVelocity">0.300000</hkparam>\n'
    '\t\t\t<hkparam name="snapMaxLinearDistance">0.030000</hkparam>\n'
    '\t\t\t<hkparam name="snapMaxAngularDistance">0.100000</hkparam>\n'
    '\t\t</hkobject>\n'
    '\t</hkparam>\n'
    '\t<hkparam name="durationToBlend">0.500000</hkparam>\n'
    '</hkobject>')
_F_GLOBAL = ('FLAG_IS_LOCAL_WILDCARD|FLAG_IS_GLOBAL_WILDCARD|'
             'FLAG_DISABLE_CONDITION')

# When the death pose clip fires `Ragdoll` (releases the keyframed bodies
# into the limp ragdoll): 8 frames after AnimateToRagdoll entry, the wolf's
# authored Death-clip timing (`Ragdoll:0.267`). Shared between the graph
# clip trigger and the animationdata cache block.
_RAGDOLL_RELEASE_T = 0.266667

_TRIGGER_TMPL = '''<hkobject>
\t<hkparam name="localTime">{time:.6f}</hkparam>
\t<hkparam name="event">
\t\t<hkobject>
\t\t\t<hkparam name="id">{event_id}</hkparam>
\t\t\t<hkparam name="payload">null</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="relativeToEndOfClip">{rel}</hkparam>
\t<hkparam name="acyclic">false</hkparam>
\t<hkparam name="isAnnotation">false</hkparam>
</hkobject>'''

_VARIABLE_INFO_TMPL = '''<hkobject>
\t<hkparam name="role">
\t\t<hkobject>
\t\t\t<hkparam name="role">ROLE_DEFAULT</hkparam>
\t\t\t<hkparam name="flags">0</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="type">VARIABLE_TYPE_{vtype}</hkparam>
</hkobject>'''

_BINDING_TMPL = '''<hkobject>
\t<hkparam name="memberPath">{member}</hkparam>
\t<hkparam name="variableIndex">{var_index}</hkparam>
\t<hkparam name="bitIndex">-1</hkparam>
\t<hkparam name="bindingType">BINDING_TYPE_VARIABLE</hkparam>
</hkobject>'''

# The engine-side graph interface: SSE's movement controller / combat / AI
# bind these by name at graph init (every vanilla creature behavior declares
# them — vanilla dogbehavior has 65 variables; this is the engine-set/read
# subset).  A graph with NO variables leaves the movement hookup dead: the
# actor plays its start state forever and never walks or reacts.
# Third field = initial word value.  Vanilla dogbehavior inits IsAttackReady
# and bEquipOK to 1 — the combat controller reads them before ever sending
# an attackStart_* event, so a 0 default means the actor follows its target
# but NEVER attacks (2026-07-09 no-attacks root cause, with the weaponDraw
# reply below).  iCombatStance is engine-written on stance changes and
# drives the StartCombat/StopCombat expression pair.
ENGINE_VARIABLES = [
    ('Speed', 'REAL', 0), ('Direction', 'REAL', 0), ('TurnDelta', 'REAL', 0),
    ('TurnDeltaDamped', 'REAL', 0), ('SpeedSampled', 'REAL', 0),
    ('staggerMagnitude', 'REAL', 0), ('staggerDirection', 'REAL', 0),
    ('iState', 'INT32', 0), ('iGetUpType', 'INT32', 0),
    ('iCharacterSelector', 'INT32', 0), ('iCombatStance', 'INT32', 0),
    ('IsAttacking', 'BOOL', 0), ('IsAttackReady', 'BOOL', 1),
    ('bEquipOK', 'BOOL', 1),
    # Weapon-class state the ENGINE writes when it equips something, and which
    # the equip state machine switches on. Vanilla weapon-using creature graphs
    # declare these (draugr/falmer) and bare-handed ones do not (wolf/chaurus);
    # ck-cmd's TES4 variable template lists them too (ConvertNif.cpp:6634-6638).
    # Without them the engine has no way to tell the graph WHICH draw animation
    # to play, so the weapon never leaves its sheath node.
    ('iRightHandType', 'INT32', 0), ('iLeftHandType', 'INT32', 0),
    ('iEquippedItemState', 'INT32', 0), ('IsUnequipping', 'BOOL', 0),
    ('IsRecoiling', 'BOOL', 0), ('IsStaggering', 'BOOL', 0),
    ('IsBleedingOut', 'BOOL', 0), ('IsBashing', 'BOOL', 0),
    ('bAnimationDriven', 'BOOL', 0), ('bAllowRotation', 'BOOL', 0),
    ('bHeadTracking', 'BOOL', 0), ('bCanHeadTrack', 'BOOL', 0),
    ('bDisableHeadTrack', 'BOOL', 0), ('bForceIdleStop', 'BOOL', 0),
]


def movement_type_names(name: str) -> list:
    """The creature's engine movement-type names — the CONTRACT that makes an
    actor movable at all (2026-07-09, the tc-can't-move root cause).

    The engine registers an actor's movement types by enumerating the ROOT
    behavior graph's variables named `iState_<X>` and looking up the MOVT
    record whose MNAM == <X> (ck-cmd RetargetCreature.cpp does exactly this
    rename+MOVT-clone when retargeting creatures; vanilla dogbehavior
    declares iState_DogDefault/iState_DogRun matching MOVT MNAM DogDefault/
    DogRun). A graph with NO iState_* variables gives the movement
    controller ZERO movement types: the actor cannot move even under
    console `tc` control, no locomotion events are ever sent, and it idles
    forever — records, packages, clips and cache all being correct.

    These names are declared as INT32 graph variables here AND emitted as
    MOVT records by tes5_import/creature_races.py (via the manifest), so
    consistency is by construction, like the ATKE attack events.
    """
    base = f'TES4{name.lower()}'
    return [f'{base}Default', f'{base}Run']


def build_behavior_xml(behavior_name: str, clips: dict,
                       hit_times: dict = None,
                       movement_types: list = None,
                       speeds: dict = None,
                       ragdoll: dict = None,
                       sound_events: list = None,
                       vocal_states: list = None) -> str:
    """The generated v1 state machine (see module docstring).

    hit_times: {state_name: [seconds]} — Oblivion 'Hit' text-key times for
    attack clips, emitted as preHitFrame/HitFrame triggers (the engine's
    attack-damage contract; without HitFrame an attack never deals damage).

    sound_events: the FULLY-QUALIFIED `SoundPlay.<SNDR EditorID>` names this
    creature's clips trigger. Every one must be declared in the graph's own
    event table or the annotation resolves to no event and is dropped — an
    animationdata trigger is dispatched by matching its text against this
    table, NOT by parsing the payload at play time. Vanilla does exactly this:
    chickenbehavior.hkx declares `SoundPlay.NPCChickenPeck` /
    `SoundPlay.NPCChickenScratch`, wolfbehavior.hkx declares
    `SoundPlay.NPCDogPantLPMSD` + `SoundStop.NPCDogPantLPMSD`, matching their
    animationdata triggers verbatim. The bare `SoundPlay` entry those graphs
    also carry is the inert leftover, not the mechanism.

    vocal_states: [(state_name, enter_event, anim_stem)] single-play vocal
    idle states (CSDT Idle/Aware slots), entered via the engine's idle
    system (ActionIdle/ActionIdleWarn IDLE records) and returning through
    returnToDefault. Each plays its OWN annotation-carrying copy of the
    idle animation so the sound fires once per entry, never per loop.

    movement_types: MOVT MNAM strings (movement_type_names()) declared as
    `iState_<X>` INT32 variables — the engine's movement-type registration
    contract; without them the actor cannot move at all.

    speeds: {'walk': u/s, 'run': u/s, ...} clip root-motion speeds — anchor
    weights for the MoveForward parametric walk/run blend (vanilla
    ForwardWalkBlend: children weighted by natural clip speed, blend
    parameter bound to SpeedSampled, flags=17 SYNC|PARAMETRIC).

    ragdoll: hkx_ragdoll.ragdoll_info() dict — enables the Fully Ragdoll
    death state (DeathAnimation/Ragdoll/RagdollInstant routing, a
    structural clone of the vanilla dogbehavior root SM state 4). Oblivion
    creatures have no death animations: death IS the ragdoll.
    """
    hit_times = hit_times or {}
    movement_types = movement_types or []
    speeds = speeds or {}
    # ---- event vocabulary: standard + per-attack ----
    events = ['moveStart', 'moveStop', 'moveForward', 'moveBackward',
              'turnLeft', 'turnRight', 'turnStop', 'swimStart', 'swimStop',
              'recoilStart', 'recoilStop', 'recoilLargeStart',
              'staggerStart', 'staggerStop',
              'combatStanceStart', 'combatStanceStop',
              'weaponDraw', 'weaponSheathe', 'weaponSwing',
              'attackStop', 'returnToDefault', 'deathStart', 'IdleStop',
              'DeathAnimation', 'Ragdoll', 'RagdollInstant', 'GetUpBegin',
              'AddRagdollToWorld', 'RemoveCharacterControllerFromWorld',
              'SoundPlay', 'preHitFrame', 'HitFrame',
              'FootFront', 'FootBack', 'FootLeft', 'FootRight']
    # Vocal idle enter-events (the IDLE records' ENAM strings)
    events += [evt for _s, evt, _a in (vocal_states or [])]
    # Qualified sound events: one table entry per distinct
    # `SoundPlay.<SNDR EditorID>` the clips actually fire (see docstring).
    events += [e for e in dict.fromkeys(sound_events or []) if e not in events]
    attack_events = build_attack_events(clips)
    events += attack_events
    # One enter-event per equip/unequip state (see EQUIP_STANCES); the root
    # wildcard routes weaponDraw/weaponSheathe to whichever matches the
    # engine-set iRightHandType.
    equip_events = []
    for stance in sorted(clips.get('equip', {})):
        equip_events.append(f'equipStart_{stance}')
        if clips['equip'][stance][1]:
            equip_events.append(f'unequipStart_{stance}')
    events += equip_events
    eid = {n: i for i, n in enumerate(events)}

    if not clips['idle']:
        raise ValueError('creature has no idle clip')

    pf = HkxPackfile(first_id=80)

    # blend effect: smooth 0.3s (vanilla locomotion default)
    fx_smooth = pf.add('hkbBlendingTransitionEffect')
    for obj, nm, dur, mode in ((fx_smooth, 'BlendSmooth', 0.3,
                                'SELF_TRANSITION_MODE_CONTINUE_IF_CYCLIC'),):
        obj.param('variableBindingSet', 'null')
        obj.param('userData', 0)
        obj.param('name', nm)
        obj.param('selfTransitionMode', mode)
        obj.param('eventMode', 'EVENT_MODE_DEFAULT')
        obj.param('duration', f'{dur:.6f}')
        obj.param('toGeneratorStartTimeFraction', '0.000000')
        obj.param('flags', 'FLAG_IGNORE_FROM_WORLD_FROM_MODEL')
        obj.param('endMode', 'END_MODE_NONE')
        obj.param('blendCurve', 'BLEND_CURVE_SMOOTH')

    # variable table is fixed up-front so bindings can reference indices.
    # iState family: vanilla-style movement-type tags (dogbehavior:
    # iState_DogDefault=30/iState_DogRun=31, iState initialized to Default).
    variables = ([(n, t, iv) for n, t, iv in ENGINE_VARIABLES]
                 + [(f'iState_{mt}', 'INT32', 30 + i)
                    for i, mt in enumerate(movement_types)])
    var_values = [30 if n == 'iState' else iv for n, _t, iv in variables]
    vidx = {n: i for i, (n, _t, _iv) in enumerate(variables)}

    def _binding_set(pairs):
        """hkbVariableBindingSet from (memberPath, variable name) pairs."""
        b = pf.add('hkbVariableBindingSet')
        b.param_raw('bindings',
                    '\n'.join(_BINDING_TMPL.format(member=m,
                                                   var_index=vidx[v])
                              for m, v in pairs),
                    numelements=len(pairs))
        b.param('indexOfBindingToEnable', -1)
        return b

    def _clip(name, kf_path, looping, triggers_ref='null', rate=1.0,
              anim=None):
        # anim: override the animation FILE stem. Annotations live in the
        # file, so a state whose events differ from the kf's other states
        # (vocal idles) — or must have none (the ragdoll pose) — points at
        # its own copy instead of the shared one.
        clip = pf.add('hkbClipGenerator')
        clip.param('variableBindingSet', 'null')
        clip.param('userData', 0)
        clip.param('name', name)
        clip.param('animationName',
                   'Animations\\' + (anim or _clip_state_name(kf_path))
                   + '.hkx')
        clip.param('triggers', triggers_ref)
        clip.param('cropStartAmountLocalTime', '0.000000')
        clip.param('cropEndAmountLocalTime', '0.000000')
        clip.param('startTime', '0.000000')
        clip.param('playbackSpeed', f'{rate:.6f}')
        clip.param('enforcedDuration', '0.000000')
        clip.param('userControlledTimeFraction', '0.000000')
        clip.param('animationBindingIndex', -1)
        clip.param('mode', 'MODE_LOOPING' if looping else 'MODE_SINGLE_PLAY')
        clip.param('flags', 0)
        return clip

    def _trans_array(items):
        """hkbStateMachineTransitionInfoArray from
        (event_id, to_state, flags) tuples."""
        arr = pf.add('hkbStateMachineTransitionInfoArray')
        arr.param_raw(
            'transitions',
            '\n'.join(_TRANSITION_TMPL.format(effect=fx_smooth.ref,
                                              event_id=e, to_state=s,
                                              flags=f)
                      for e, s, f in items),
            numelements=len(items))
        return arr

    def _events_array(names):
        arr = pf.add('hkbStateMachineEventPropertyArray')
        arr.param_raw('events', '\n'.join(
            '<hkobject>\n'
            f'\t<hkparam name="id">{eid[n]}</hkparam>\n'
            '\t<hkparam name="payload">null</hkparam>\n'
            '</hkobject>' for n in names), numelements=len(names))
        return arr

    def _state(state_id, name, generator_ref, transitions=None,
               exit_events=None, enter_events=None):
        # referenced objects must be added BEFORE the stateInfo (hkxcmd's
        # parser rejects forward references)
        trans_ref = _trans_array(transitions).ref if transitions else 'null'
        enter_ref = (_events_array(enter_events).ref if enter_events
                     else 'null')
        exit_ref = _events_array(exit_events).ref if exit_events else 'null'
        st = pf.add('hkbStateMachineStateInfo')
        st.param('variableBindingSet', 'null')
        st.param_array('listeners', [])
        st.param('enterNotifyEvents', enter_ref)
        st.param('exitNotifyEvents', exit_ref)
        st.param('transitions', trans_ref)
        st.param('generator', generator_ref)
        st.param('name', name)
        st.param('stateId', state_id)
        st.param('probability', '1.000000')
        st.param('enable', True)
        return st

    def _make_sm(name, states, start_id=0, wildcard_ref='null'):
        m = pf.add('hkbStateMachine')
        m.param('variableBindingSet', 'null')
        m.param('userData', 0)
        m.param('name', name)
        m.param_raw('eventToSendWhenStateOrTransitionChanges', (
            '<hkobject>\n\t<hkparam name="id">-1</hkparam>\n'
            '\t<hkparam name="payload">null</hkparam>\n</hkobject>'))
        m.param('startStateChooser', 'null')
        m.param('startStateId', start_id)
        m.param('returnToPreviousStateEventId', -1)
        m.param('randomTransitionEventId', -1)
        m.param('transitionToNextHigherStateEventId', -1)
        m.param('transitionToNextLowerStateEventId', -1)
        m.param('syncVariableIndex', -1)
        m.param('wrapAroundStateId', False)
        m.param('maxSimultaneousTransitions', 32)
        m.param('startStateMode', 'START_STATE_MODE_DEFAULT')
        m.param('selfTransitionMode', 'SELF_TRANSITION_MODE_NO_TRANSITION')
        m.param_array('states', [s.ref for s in states])
        m.param('wildcardTransitions', wildcard_ref)
        return m

    def _parametric_blend(name, plan):
        """Vanilla-style SYNC|PARAMETRIC speed blend: children are the same
        clips at scaled playbackSpeeds, each anchored (weight) at its true
        animation speed, blendParameter driven by SpeedSampled."""
        children = []
        for cnm, kf, rate, anchor in plan:
            child_clip = _clip(cnm, kf, True, rate=rate)
            ch = pf.add('hkbBlenderGeneratorChild')
            ch.param('variableBindingSet', 'null')
            ch.param('generator', child_clip.ref)
            ch.param('boneWeights', 'null')
            ch.param('weight', f'{anchor:.6f}')
            ch.param('worldFromModelWeight', '1.000000')
            children.append(ch)
        bind = _binding_set([('blendParameter', 'SpeedSampled')])
        blender = pf.add('hkbBlenderGenerator')
        blender.param('variableBindingSet', bind.ref)
        blender.param('userData', 0)
        blender.param('name', name)
        blender.param('referencePoseWeightThreshold', '0.000000')
        blender.param('blendParameter', '1.000000')
        blender.param('minCyclicBlendParameter', '0.000000')
        blender.param('maxCyclicBlendParameter', '1.000000')
        blender.param('indexOfSyncMasterChild', -1)
        blender.param('flags', 17)
        blender.param('subtractLastChild', False)
        blender.param_array('children', [c.ref for c in children])
        return blender

    # =====================================================================
    # Nested state machines (the vanilla quadruped topology, 2026-07-16).
    # The old FLAT graph made every engine event a root wildcard: combat
    # facing-adjustments (turnLeft/turnRight, sent continuously) hijacked
    # the whole graph — visible as constant left/right body-whipping — and
    # aborted every attack mid-swing (the "never attacks" report).  Vanilla
    # nests turns inside the Standing machine (unreachable while moving or
    # attacking) and enters attacks only via LOCAL transitions from
    # DefaultState.
    # =====================================================================
    loco = clips['locomotion']

    # ---- LocomotionBehavior: Forward(0) <-> Backward(1) ----
    loco_sm = None
    if 'MoveForward' in loco:
        fplan = speed_blend_plan(clips, speeds)
        fwd_gen = (_parametric_blend('ForwardSpeedBlend', fplan) if fplan
                   else _clip('MoveForward', loco['MoveForward'], True))
        has_back = 'MoveBackward' in loco
        fwd_state = _state(
            0, 'ForwardLocomotionState', fwd_gen.ref,
            transitions=([(eid['moveBackward'], 1, _F_LOCAL)]
                         if has_back else None))
        loco_states = [fwd_state]
        if has_back:
            bplan = backward_blend_plan(clips, speeds)
            back_gen = (_parametric_blend('BackwardSpeedBlend', bplan)
                        if bplan
                        else _clip('MoveBackward', loco['MoveBackward'],
                                   True))
            loco_states.append(_state(
                1, 'BackwardLocomotionState', back_gen.ref,
                transitions=[(eid['moveForward'], 0, _F_LOCAL)]))
        loco_sm = _make_sm('LocomotionBehavior', loco_states)

    # ---- StandingIdleBehavior: NonCombatIdle(0) <-> CombatIdle(1) ----
    idle_clip = _clip('Idle', clips['idle'], True)
    combat_clip = _clip('CombatStance', clips['idle'], True)
    standing_idle_sm = _make_sm('StandingIdleBehavior', [
        _state(0, 'NonCombatIdleState', idle_clip.ref,
               transitions=[(eid['combatStanceStart'], 1, _F_LOCAL)]),
        _state(1, 'CombatIdleState', combat_clip.ref,
               transitions=[(eid['combatStanceStop'], 0, _F_LOCAL)]),
    ])

    # ---- StandingBehavior: idle switch + looping turn-in-place states ----
    has_tr = 'TurnRight' in loco
    has_tl = 'TurnLeft' in loco
    idle_trans = []
    if has_tr:
        idle_trans.append((eid['turnRight'], 1, _F_LOCAL))
    if has_tl:
        idle_trans.append((eid['turnLeft'], 2, _F_LOCAL))
    standing_states = [_state(0, 'StandingIdleState', standing_idle_sm.ref,
                              transitions=idle_trans or None)]
    if has_tr:
        tr_trans = [(eid['turnStop'], 0, _F_LOCAL)]
        if has_tl:
            tr_trans.insert(0, (eid['turnLeft'], 2, _F_LOCAL))
        standing_states.append(_state(
            1, 'LoopingTurnRight',
            _clip('TurnRight', loco['TurnRight'], True).ref,
            transitions=tr_trans))
    if has_tl:
        tl_trans = [(eid['turnStop'], 0, _F_LOCAL)]
        if has_tr:
            tl_trans.insert(0, (eid['turnRight'], 1, _F_LOCAL))
        standing_states.append(_state(
            2, 'LoopingTurnLeft',
            _clip('TurnLeft', loco['TurnLeft'], True).ref,
            transitions=tl_trans))
    standing_sm = _make_sm('StandingBehavior', standing_states)

    # ---- DefaultBehavior: Standing(0) <-> Locomotion(1) ----
    default_states = [_state(
        0, 'StandingState', standing_sm.ref,
        transitions=([(eid['moveStart'], 1, _F_LOCAL)] if loco_sm else None))]
    if loco_sm:
        default_states.append(_state(
            1, 'LocomotionState', loco_sm.ref,
            transitions=[(eid['moveStop'], 0, _F_LOCAL)]))
    default_sm = _make_sm('DefaultBehavior', default_states)

    # ---- root state machine: DefaultState + single-play interrupts ----
    # Attack states wrap their clip in the vanilla IsActive modifier: while
    # the state is active it drives IsAttacking=1 (the combat controller's
    # in-progress flag), bAllowRotation=1 (target tracking during the
    # swing), bDisableHeadTrack=1.  Without IsAttacking the engine keeps
    # steering mid-swing.
    attack_isactive_bind = _binding_set([
        ('bIsActive0', 'IsAttacking'),
        ('bIsActive1', 'bAllowRotation'),
        ('bIsActive2', 'bDisableHeadTrack')])
    attack_isactive = pf.add('BSIsActiveModifier')
    attack_isactive.param('variableBindingSet', attack_isactive_bind.ref)
    attack_isactive.param('userData', 2)
    attack_isactive.param('name', 'BSIsActiveModifier_IsAttacking')
    attack_isactive.param('enable', True)
    for i in range(5):
        attack_isactive.param(f'bIsActive{i}', False)
        attack_isactive.param(f'bInvertActive{i}', False)
    attack_ml = pf.add('hkbModifierList')
    attack_ml.param('variableBindingSet', 'null')
    attack_ml.param('userData', 1)
    attack_ml.param('name', 'AttackModifierList')
    attack_ml.param('enable', True)
    attack_ml.param_array('modifiers', [attack_isactive.ref])

    def _clip_triggers(st_name, end_evt):
        items = []
        for t in hit_times.get(st_name, []):
            items.append(_TRIGGER_TMPL.format(
                time=max(0.0, t - 0.3), event_id=eid['weaponSwing'],
                rel='false'))
            items.append(_TRIGGER_TMPL.format(
                time=max(0.0, t - 0.1), event_id=eid['preHitFrame'],
                rel='false'))
            items.append(_TRIGGER_TMPL.format(
                time=t, event_id=eid['HitFrame'], rel='false'))
        if end_evt:
            items.append(_TRIGGER_TMPL.format(
                time=0.0, event_id=eid[end_evt], rel='true'))
        if not items:
            return 'null'
        trig = pf.add('hkbClipTriggerArray')
        trig.param_raw('triggers', '\n'.join(items), numelements=len(items))
        return trig.ref

    root_states_inner = []
    next_id = 1
    default_trans = []      # attackStart_* -> attack states (LOCAL)
    root_wilds = []

    for st, (_names, enter, stop_evt) in SINGLE_PLAY.items():
        if st not in clips['single']:
            continue
        end_evt = 'returnToDefault' if st != 'Death' else None
        clip = _clip(st, clips['single'][st], False,
                     _clip_triggers(st, end_evt))
        root_states_inner.append(_state(
            next_id, f'{st}State', clip.ref,
            exit_events=[stop_evt] if stop_evt else None))
        root_wilds.append((eid[enter], next_id, _F_WILD if st != 'Death'
                           else _F_GLOBAL))
        if st == 'Recoil':
            root_wilds.append((eid['recoilLargeStart'], next_id, _F_WILD))
        next_id += 1

    if 'Swim' in loco:
        swim_clip = _clip('Swim', loco['Swim'], True)
        root_states_inner.append(_state(
            next_id, 'SwimState', swim_clip.ref,
            transitions=[(eid['swimStop'], 0, _F_LOCAL)]))
        root_wilds.append((eid['swimStart'], next_id, _F_WILD))
        next_id += 1

    for kf, evt in zip(clips['attacks'], build_attack_events(clips)):
        st_name = f'Attack_{_clip_state_name(kf)}'
        clip = _clip(st_name, kf, False,
                     _clip_triggers(st_name, 'returnToDefault'))
        mg = pf.add('hkbModifierGenerator')
        mg.param('variableBindingSet', 'null')
        mg.param('userData', 1)
        mg.param('name', f'{st_name}_MG')
        mg.param('modifier', attack_ml.ref)
        mg.param('generator', clip.ref)
        root_states_inner.append(_state(
            next_id, f'{st_name}State', mg.ref,
            exit_events=['attackStop']))
        default_trans.append((eid[evt], next_id, _F_LOCAL))
        next_id += 1

    # Equip / unequip states. The engine sends weaponDraw when it wants the
    # actor armed; the expression modifier below translates that into the
    # per-class equipStart_* event matching the engine-set iRightHandType, and
    # the clip's END trigger replies weaponDraw so the combat controller knows
    # the actor is ready. Sheathing is the mirror image.
    equip_dispatch = []
    for stance, (eq, uneq) in sorted(clips.get('equip', {}).items()):
        hand_types = EQUIP_STANCES[stance][2]
        for kind, kf, reply in (('equip', eq, 'weaponDraw'),
                                ('unequip', uneq, 'weaponSheathe')):
            if kf is None:
                continue
            st_name = f'{kind.capitalize()}_{stance}'
            evt = f'{kind}Start_{stance}'
            clip = _clip(st_name, kf, False, _clip_triggers(st_name, reply))
            root_states_inner.append(_state(
                next_id, f'{st_name}State', clip.ref,
                transitions=[(eid['returnToDefault'], 0, _F_LOCAL)]))
            root_wilds.append((eid[evt], next_id, _F_WILD))
            next_id += 1
            equip_dispatch.append((kind, evt, hand_types))

    # Vocal idle states (CSDT Idle/Aware slots). Single-play — the sound
    # annotation lives in the state's OWN animation file, so it fires once
    # per entry, and entry is paced by the engine's idle system through the
    # ActionIdle / ActionIdleWarn IDLE records (tes5_import/creature_idles),
    # exactly like vanilla WolfIdleHowl / WolfIdleWarn. Embedding the sound
    # in the looping Idle/CombatStance clips instead made it fire every
    # cycle, in life and in the ragdoll wrapper states after death.
    for st_name, evt, stem in (vocal_states or []):
        clip = _clip(st_name, clips['idle'], False,
                     _clip_triggers(st_name, 'returnToDefault'), anim=stem)
        root_states_inner.append(_state(
            next_id, f'{st_name}State', clip.ref))
        root_wilds.append((eid[evt], next_id, _F_WILD))
        next_id += 1

    equip_eem = None
    if equip_dispatch:
        # weaponDraw/weaponSheathe -> the class-specific enter event. Guarded on
        # iRightHandType so a bow draw plays bowequip and a mace draw plays
        # onehandequip; the H2H entry (hand type 0) doubles as the fallback.
        exprs = []
        for kind, evt, hand_types in equip_dispatch:
            src = 'weaponDraw' if kind == 'equip' else 'weaponSheathe'
            cond = ' || '.join(f'(iRightHandType == {t})' for t in hand_types)
            exprs.append(f'{evt} if (({src}) && ({cond}))')
        arr = pf.add('hkbExpressionDataArray')
        arr.param_raw('expressionsData', '\n'.join(
            '<hkobject>\n'
            f'\t<hkparam name="expression">{e}</hkparam>\n'
            '\t<hkparam name="assignmentVariableIndex">-1</hkparam>\n'
            '\t<hkparam name="assignmentEventIndex">-1</hkparam>\n'
            '\t<hkparam name="eventMode">EVENT_MODE_SEND_ON_FALSE_TO_TRUE'
            '</hkparam>\n'
            '</hkobject>' for e in exprs), numelements=len(exprs))
        eem = pf.add('hkbEvaluateExpressionModifier')
        eem.param('variableBindingSet', 'null')
        eem.param('userData', 2)
        eem.param('name', 'EquipDispatch_EEM')
        eem.param('enable', True)
        eem.param('expressions', arr.ref)
        equip_eem = eem

    default_state = _state(0, 'DefaultState', default_sm.ref,
                           transitions=default_trans or None)
    root_states_inner.insert(0, default_state)

    root_wilds.append((eid['returnToDefault'], 0, _F_GLOBAL))
    root_wilds.append((eid['IdleStop'], 0, _F_WILD))
    wild = _trans_array(root_wilds)

    sm = _make_sm(f'{behavior_name}Root', root_states_inner,
                  start_id=0, wildcard_ref=wild.ref)

    # ---- variables / events tables ----
    strings = pf.add('hkbBehaviorGraphStringData')
    strings.param_strings('eventNames', events)
    strings.param_array('attributeNames', [])
    strings.param_strings('variableNames', [n for n, _t, _iv in variables])
    strings.param_array('characterPropertyNames', [])

    values = pf.add('hkbVariableValueSet')
    values.param_structs('wordVariableValues',
                         [[('value', v)] for v in var_values])
    values.param_array('quadVariableValues', [])
    values.param_array('variantVariableValues', [])

    gdata = pf.add('hkbBehaviorGraphData')
    gdata.param_array('attributeDefaults', [])
    gdata.param_raw('variableInfos',
                    '\n'.join(_VARIABLE_INFO_TMPL.format(vtype=t)
                              for _n, t, _iv in variables),
                    numelements=len(variables))
    gdata.param_structs('characterPropertyInfos', [])
    gdata.param_structs('eventInfos', [[('flags', 0)]] * len(events))
    gdata.param('variableInitialValues', values.ref)
    gdata.param('stringData', strings.ref)

    # ---- engine movement hookup (mirrors the vanilla quadruped root) ----
    # The engine samples the graph's animation-driven movement speed through
    # a BSSpeedSamplerModifier bound to iState/Direction/Speed/SpeedSampled.
    # Without it AI pathing has no speed to drive, the actor never receives
    # movement, and it stands in its idle forever (combat can't approach
    # either).  Vanilla wraps the whole locomotion state machine in a
    # hkbModifierGenerator under a single-state root state machine; copy
    # that layout verbatim (userData values included).
    sampler_binds = _binding_set([('state', 'iState'),
                                  ('direction', 'Direction'),
                                  ('goalSpeed', 'Speed'),
                                  ('speedOut', 'SpeedSampled')])

    sampler = pf.add('BSSpeedSamplerModifier')
    sampler.param('variableBindingSet', sampler_binds.ref)
    sampler.param('userData', 2)
    sampler.param('name', 'BSSpeedSamplerModifier')
    sampler.param('enable', True)
    sampler.param('state', -1)
    sampler.param('direction', '0.000000')
    sampler.param('goalSpeed', '0.000000')
    sampler.param('speedOut', '0.000000')

    # ---- combat stance handshake (verbatim vanilla quadruped layout) ----
    # The engine's ActionDraw routes combatStanceStart (IDLE record); combat
    # then WAITS for the graph to reply with a weaponDraw event before ever
    # sending an attackStart_*.  Vanilla sends that reply from a root-level
    # hkbEventDrivenModifier/hkbEvaluateExpressionModifier pair (StartCombat/
    # StopCombat), NOT from state notify events — an actor without this pair
    # chases its target forever and never attacks.
    def _combat_eem(name, stance_val, reply_evt):
        arr = pf.add('hkbExpressionDataArray')
        arr.param_raw('expressionsData', (
            '<hkobject>\n'
            f'\t<hkparam name="expression">iCombatStance = {stance_val}'
            '</hkparam>\n'
            '\t<hkparam name="assignmentVariableIndex">-1</hkparam>\n'
            '\t<hkparam name="assignmentEventIndex">-1</hkparam>\n'
            '\t<hkparam name="eventMode">EVENT_MODE_SEND_ONCE</hkparam>\n'
            '</hkobject>\n'
            '<hkobject>\n'
            f'\t<hkparam name="expression">{reply_evt} if '
            f'(iCombatStance == {stance_val})</hkparam>\n'
            '\t<hkparam name="assignmentVariableIndex">-1</hkparam>\n'
            '\t<hkparam name="assignmentEventIndex">-1</hkparam>\n'
            '\t<hkparam name="eventMode">EVENT_MODE_SEND_ON_FALSE_TO_TRUE'
            '</hkparam>\n'
            '</hkobject>'), numelements=2)
        eem = pf.add('hkbEvaluateExpressionModifier')
        eem.param('variableBindingSet', 'null')
        eem.param('userData', 2)
        eem.param('name', name)
        eem.param('enable', True)
        eem.param('expressions', arr.ref)
        return eem

    def _edm(name, modifier_ref, activate, deactivate, active_by_default):
        edm = pf.add('hkbEventDrivenModifier')
        edm.param('variableBindingSet', 'null')
        edm.param('userData', 1)
        edm.param('name', name)
        edm.param('enable', True)
        edm.param('modifier', modifier_ref)
        edm.param('activateEventId', activate)
        edm.param('deactivateEventId', deactivate)
        edm.param('activeByDefault', active_by_default)
        return edm

    stop_combat = _edm('StopCombat_EDM',
                       _combat_eem('StopCombat_EEM', 0, 'weaponSheathe').ref,
                       eid['combatStanceStop'], eid['combatStanceStart'],
                       True)
    start_combat = _edm('StartCombat_EDM',
                        _combat_eem('StartCombat_EEM', 1, 'weaponDraw').ref,
                        eid['combatStanceStart'], eid['combatStanceStop'],
                        False)

    # ---- live ragdoll tracking (vanilla dogbehavior 'Root Mod List') ----
    # While the actor is ALIVE the ragdoll rigid bodies must be KEYFRAMED to
    # the animation pose and PD-driven toward it (hkbKeyframeBonesModifier +
    # hkbRigidBodyRagdollControlsModifier, both present in every vanilla
    # creature root state).  Without them the bodies sit wherever the file
    # left them, so the moment the death ragdoll activates, the corpse snaps
    # to those stale transforms — the 2026-08-07 "jumps sideways on death /
    # collision beside the body / sinks through the floor" report.
    #
    # The bone list is `keyframe_lower`, NOT every ragdoll bone: vanilla's
    # modifier is literally named `KeyframeLowerBody` and omits the tail,
    # neck and head so those chains hang free under physics on a living
    # creature.  Keyframing ALL of them pins the entire ragdoll to the
    # animation pose (see ragdoll._keyframe_bone_sets — the 2026-08-08
    # rigid-corpse root cause).
    live_track = []
    if ragdoll:
        kf_bones = pf.add('hkbBoneIndexArray')
        kf_bones.param('variableBindingSet', 'null')
        kf_bones.param_array('boneIndices', ragdoll['keyframe_lower'])
        kf_mod = pf.add('hkbKeyframeBonesModifier')
        kf_mod.param('variableBindingSet', 'null')
        kf_mod.param('userData', 1)
        kf_mod.param('name', 'KeyframeLowerBody')
        kf_mod.param('enable', True)
        kf_mod.param_raw('keyframeInfo', '', numelements=0)
        kf_mod.param('keyframedBonesList', kf_bones.ref)

        drive_bones = pf.add('hkbBoneIndexArray')
        drive_bones.param('variableBindingSet', 'null')
        drive_bones.param_array('boneIndices', [])
        drive_mod = pf.add('hkbRigidBodyRagdollControlsModifier')
        drive_mod.param('variableBindingSet', 'null')
        drive_mod.param('userData', 1)
        drive_mod.param('name', 'DriveRagdollRB')
        drive_mod.param('enable', True)
        drive_mod.param_raw('controlData', _RB_RAGDOLL_CONTROL_DATA)
        drive_mod.param('bones', drive_bones.ref)
        live_track = [kf_mod.ref, drive_mod.ref]

    mod_list = pf.add('hkbModifierList')
    mod_list.param('variableBindingSet', 'null')
    mod_list.param('userData', 1)
    mod_list.param('name', 'RootModifierList')
    mod_list.param('enable', True)
    # EquipDispatch must run alongside the combat pair: it turns the engine's
    # weaponDraw/weaponSheathe into the per-weapon-class equip event.
    mod_list.param_array('modifiers',
                         live_track
                         + [stop_combat.ref, start_combat.ref, sampler.ref]
                         + ([equip_eem.ref] if equip_eem is not None else []))

    mod_gen = pf.add('hkbModifierGenerator')
    mod_gen.param('variableBindingSet', 'null')
    mod_gen.param('userData', 1)
    mod_gen.param('name', 'RootModifierGenerator')
    mod_gen.param('modifier', mod_list.ref)
    mod_gen.param('generator', sm.ref)

    def _root_state(state_id, name, generator_ref, enter_evt_name=None,
                    transitions_ref='null'):
        enter_ref = 'null'
        if enter_evt_name:
            names = ([enter_evt_name] if isinstance(enter_evt_name, str)
                     else list(enter_evt_name))
            arr = pf.add('hkbStateMachineEventPropertyArray')
            arr.param_raw('events', '\n'.join(
                '<hkobject>\n'
                f'\t<hkparam name="id">{eid[n]}</hkparam>\n'
                '\t<hkparam name="payload">null</hkparam>\n'
                '</hkobject>' for n in names), numelements=len(names))
            enter_ref = arr.ref
        st = pf.add('hkbStateMachineStateInfo')
        st.param('variableBindingSet', 'null')
        st.param_array('listeners', [])
        st.param('enterNotifyEvents', enter_ref)
        st.param('exitNotifyEvents', 'null')
        st.param('transitions', transitions_ref)
        st.param('generator', generator_ref)
        st.param('name', name)
        st.param('stateId', state_id)
        st.param('probability', '1.000000')
        st.param('enable', True)
        return st

    root_states = [_root_state(0, 'Root', mod_gen.ref)]
    root_wild_ref = 'null'

    # ---- death / ragdoll states (vanilla dogbehavior states 3 + 4) ----
    # Oblivion creatures ship no death animations — death IS the ragdoll.
    # BOTH vanilla states are required and the split is load-bearing:
    #
    #   state 1 'AnimateToRagdoll' (vanilla #0130, entered on
    #   DeathAnimation): its enterNotifyEvents raises `AddRagdollToWorld` —
    #   THE ONLY thing in the entire pipeline that ever does.  The engine
    #   does NOT add the ragdoll on the normal kill path by itself; a
    #   2026-08-08 "simplification" that dropped this state left corpses
    #   with no ragdoll and (state 2 still removing the character
    #   controller) NO collision at all — falling through the floor,
    #   nothing activatable, pose playing forever.
    #
    #   state 2 'Fully Ragdoll' (vanilla #0117, entered on Ragdoll /
    #   RagdollInstant — fired by the contact listener, or directly by the
    #   engine when it ragdolled the actor itself: killmoves, paralysis):
    #   ModifierGenerator [FullRagdoll event-driven wrapper ->
    #   PoweredRagdoll No Matching (maxForce 0, MODE_RAGDOLL)] over the
    #   frozen pose clip, notifying RemoveCharacterControllerFromWorld.
    if ragdoll and clips['idle']:
        pb0, pb1, pb2 = ragdoll['pose_bones']

        def _powered_ragdoll(name, max_force, mode):
            bones_arr = pf.add('hkbBoneIndexArray')
            bones_arr.param('variableBindingSet', 'null')
            bones_arr.param_array('boneIndices', [])
            weights = pf.add('hkbBoneWeightArray')
            weights.param('variableBindingSet', 'null')
            weights.param_array('boneWeights', [])
            m = pf.add('hkbPoweredRagdollControlsModifier')
            m.param('variableBindingSet', 'null')
            m.param('userData', 1)
            m.param('name', name)
            m.param('enable', True)
            m.param_raw('controlData', (
                '<hkobject>\n'
                f'\t<hkparam name="maxForce">{max_force:.6f}</hkparam>\n'
                '\t<hkparam name="tau">0.800000</hkparam>\n'
                '\t<hkparam name="damping">1.000000</hkparam>\n'
                '\t<hkparam name="proportionalRecoveryVelocity">2.000000'
                '</hkparam>\n'
                '\t<hkparam name="constantRecoveryVelocity">1.000000'
                '</hkparam>\n'
                '</hkobject>'))
            m.param('bones', bones_arr.ref)
            m.param_raw('worldFromModelModeData', (
                '<hkobject>\n'
                f'\t<hkparam name="poseMatchingBone0">{pb0}</hkparam>\n'
                f'\t<hkparam name="poseMatchingBone1">{pb1}</hkparam>\n'
                f'\t<hkparam name="poseMatchingBone2">{pb2}</hkparam>\n'
                f'\t<hkparam name="mode">{mode}</hkparam>\n'
                '</hkobject>'))
            m.param('boneWeights', weights.ref)
            return m

        # Vanilla #0092 'FullRagdoll': the limp powered ragdoll is active by
        # default and released by GetUpBegin (the getup flow; inert for a
        # corpse but kept for structural parity with vanilla).
        full_rag_edm = _edm(
            'FullRagdoll',
            _powered_ragdoll('PoweredRagdoll No Matching', 0.0,
                             'WORLD_FROM_MODEL_MODE_RAGDOLL').ref,
            -1, eid['GetUpBegin'], True)

        # Pose source: a CLEAN copy of the idle animation
        # ('ragdollpose.hkx', written without annotations — an annotation in
        # a looping corpse clip voices the corpse forever, the confirmed
        # squeaking-dead-rat bug).  The clip generator MUST be registered in
        # animationdata/animationsetdata under this exact name
        # ('FullyRagdollPose' -> generate_creature_project clip_meta entry):
        # an unregistered creature clip never binds — the death state then
        # runs with a dead pose source and the whole ragdoll handoff
        # collapses into the engine's stiff-fall fallback (static corpse,
        # standing collision, model pivoting sideways about its root).
        #
        # MODE_SINGLE_PLAY at speed 1.0 — the exact vanilla death-state clip
        # semantics (dogbehavior state 3 plays Death.hkx MODE_SINGLE_PLAY;
        # state 4's pose sources are MODE_SINGLE_PLAY getup clips; NO
        # vanilla file anywhere ships playbackSpeed 0).  A single play holds
        # its LAST frame when it ends, so the corpse does not breathe or wag
        # (the 2026-08-08 report against the LOOPING idle).
        #
        # THE RAGDOLL RELEASE IS A CLIP TRIGGER, not (only) the contact
        # listener (2026-08-08, frozen-corpse root cause #2): vanilla
        # dogbehavior's Death clip (#0119) carries exactly one trigger —
        # event 81 `Ragdoll`, relativeToEndOfClip — and the wolf's
        # animationdata Death block fires `Ragdoll:0.267` absolute.  That
        # event is what moves state 3 -> 4 and releases the keyframed
        # bodies into the limp powered ragdoll; the
        # BSRagdollContactListenerModifier alone never fired for our
        # keyframed bodies, so corpses stayed rigid in their death pose
        # forever.  Vanilla's trigger sits at the end of an authored ~1s
        # dying animation; our pose source is a HELD IDLE, so the wolf's
        # early absolute timing (8 frames — enough for the engine to
        # process AddRagdollToWorld raised on state entry) is the right
        # equivalent, in BOTH the graph triggers and the animationdata
        # block (_RAGDOLL_RELEASE_T, shared with the clip_meta entry).
        pose_trig = pf.add('hkbClipTriggerArray')
        pose_trig.param_raw(
            'triggers',
            _TRIGGER_TMPL.format(time=_RAGDOLL_RELEASE_T,
                                 event_id=eid['Ragdoll'], rel='false'),
            numelements=1)
        pose_clip = _clip('FullyRagdollPose', clips['idle'], False,
                          triggers_ref=pose_trig.ref, anim='ragdollpose')
        full_rag_ml = pf.add('hkbModifierList')
        full_rag_ml.param('variableBindingSet', 'null')
        full_rag_ml.param('userData', 1)
        full_rag_ml.param('name', 'Fully Ragdoll Mod List')
        full_rag_ml.param('enable', True)
        full_rag_ml.param_array('modifiers', [full_rag_edm.ref])
        full_rag = pf.add('hkbModifierGenerator')
        full_rag.param('variableBindingSet', 'null')
        full_rag.param('userData', 1)
        full_rag.param('name', 'Fully Ragdoll Mod Gen')
        full_rag.param('modifier', full_rag_ml.ref)
        full_rag.param('generator', pose_clip.ref)

        # Vanilla #0082, verbatim: DeathAnimation and Ragdoll BLEND over
        # 0.2s; RagdollInstant switches clean.
        rag_fx = pf.add('hkbBlendingTransitionEffect')
        rag_fx.param('variableBindingSet', 'null')
        rag_fx.param('userData', 0)
        rag_fx.param('name', 'RagdollBlend')
        rag_fx.param('selfTransitionMode', 'SELF_TRANSITION_MODE_BLEND')
        rag_fx.param('eventMode', 'EVENT_MODE_DEFAULT')
        rag_fx.param('duration', '0.200000')
        rag_fx.param('toGeneratorStartTimeFraction', '0.000000')
        rag_fx.param('flags', 0)
        rag_fx.param('endMode', 'END_MODE_NONE')
        rag_fx.param('blendCurve', 'BLEND_CURVE_SMOOTH')

        # ---- vanilla state 3 'AnimateToRagdoll' (#0130) — THE state whose
        # enterNotifyEvents raises event 82 `AddRagdollToWorld`.  NOTHING
        # ELSE ever raises it: a 2026-08-08 "simplification" deleted this
        # state on the wrong theory that the engine adds the ragdoll itself
        # on the kill path, and with no AddRagdollToWorld the ragdoll never
        # entered the world — while Fully Ragdoll still removed the
        # character controller (event 87), so corpses had NO collision at
        # all: they fell through the floor, no part could be activated, and
        # the pose source played on forever (the 2026-08-08 in-game report;
        # multi-part goblins/lions just made it obvious — the rat's blend-
        # body ghost was close enough to its tiny body to pass).
        #
        # Structure is the vanilla clone: ModGen[AnimateToRagdoll ModList ->
        # KeyframeFullRagdoll (ALL ragdoll bones — the freshly added bodies
        # stay keyframed to the pose), DriveRagdollRB, CollisionListener
        # (floor contact -> Ragdoll)] over the frozen pose clip (vanilla
        # plays its authored death clip here; Oblivion creatures have none,
        # so the corpse holds pose until a keyframed body touches the
        # ground — feet touch immediately on flat ground — and the Ragdoll
        # event releases everything into the limp state).
        # `keyframe_full`, NOT every bone: vanilla leaves the deepest limb
        # leaves (toe/palm tips) UNPINNED so gravity has a purchase the frame
        # the ragdoll enters the world; the `Ragdoll` trigger then releases
        # the rest.  With every body keyframed the corpse is welded to its
        # animation pose, generates no contacts at all (so the contact
        # listener never fires), and the ragdoll handover collapses — the
        # rigid-limbs / teleport / sink-through-floor / dead-pick-geometry
        # cluster (2026-08-08).
        kf2_bones = pf.add('hkbBoneIndexArray')
        kf2_bones.param('variableBindingSet', 'null')
        kf2_bones.param_array('boneIndices', ragdoll['keyframe_full'])
        kf2 = pf.add('hkbKeyframeBonesModifier')
        kf2.param('variableBindingSet', 'null')
        kf2.param('userData', 1)
        kf2.param('name', 'KeyframeFullRagdoll')
        kf2.param('enable', True)
        kf2.param_raw('keyframeInfo', '', numelements=0)
        kf2.param('keyframedBonesList', kf2_bones.ref)

        drive2_bones = pf.add('hkbBoneIndexArray')
        drive2_bones.param('variableBindingSet', 'null')
        drive2_bones.param_array('boneIndices', [])
        drive2 = pf.add('hkbRigidBodyRagdollControlsModifier')
        drive2.param('variableBindingSet', 'null')
        drive2.param('userData', 1)
        drive2.param('name', 'DriveRagdollRB')
        drive2.param('enable', True)
        drive2.param_raw('controlData', _RB_RAGDOLL_CONTROL_DATA)
        drive2.param('bones', drive2_bones.ref)

        # `contact_bones` — the limb ROOTS plus the spine/neck/head links,
        # never the toe/palm tips or the tail (vanilla dog: 8 of 22).  A
        # scuffing toe or a dragging tail must not fire the `Ragdoll`
        # release before the body has landed.
        contact_bones = pf.add('hkbBoneIndexArray')
        contact_bones.param('variableBindingSet', 'null')
        contact_bones.param_array('boneIndices', ragdoll['contact_bones'])
        listener = pf.add('BSRagdollContactListenerModifier')
        listener.param('variableBindingSet', 'null')
        listener.param('userData', 2)
        listener.param('name', 'CollisionListener')
        listener.param('enable', True)
        listener.param_raw('contactEvent', (
            '<hkobject>\n'
            f'\t<hkparam name="id">{eid["Ragdoll"]}</hkparam>\n'
            '\t<hkparam name="payload">null</hkparam>\n'
            '</hkobject>'))
        listener.param('bones', contact_bones.ref)

        a2r_ml = pf.add('hkbModifierList')
        a2r_ml.param('variableBindingSet', 'null')
        a2r_ml.param('userData', 1)
        a2r_ml.param('name', 'AnimateToRagdoll ModList')
        a2r_ml.param('enable', True)
        a2r_ml.param_array('modifiers',
                           [kf2.ref, drive2.ref, listener.ref])
        a2r_gen = pf.add('hkbModifierGenerator')
        a2r_gen.param('variableBindingSet', 'null')
        a2r_gen.param('userData', 1)
        a2r_gen.param('name', 'AnimateToRagdoll Mod Gen')
        a2r_gen.param('modifier', a2r_ml.ref)
        a2r_gen.param('generator', pose_clip.ref)

        # state 3's own transition (#0128): Ragdoll -> Fully Ragdoll,
        # blending, plain FLAG_DISABLE_CONDITION (not a wildcard)
        a2r_trans = pf.add('hkbStateMachineTransitionInfoArray')
        a2r_trans.param_raw(
            'transitions',
            _TRANSITION_TMPL.format(effect=rag_fx.ref,
                                    event_id=eid['Ragdoll'], to_state=2,
                                    flags='FLAG_DISABLE_CONDITION'),
            numelements=1)

        root_states.append(_root_state(
            1, 'AnimateToRagdoll', a2r_gen.ref,
            'AddRagdollToWorld', a2r_trans.ref))
        root_states.append(_root_state(
            2, 'Fully Ragdoll', full_rag.ref,
            'RemoveCharacterControllerFromWorld'))

        # root wildcard, vanilla #0081 verbatim: DeathAnimation ->
        # AnimateToRagdoll (adds the ragdoll), Ragdoll / RagdollInstant ->
        # Fully Ragdoll directly (those fire when the engine has already
        # ragdolled the actor itself: killmoves, paralysis).
        root_wild = pf.add('hkbStateMachineTransitionInfoArray')
        root_wild.param_raw(
            'transitions',
            '\n'.join(_TRANSITION_TMPL.format(effect=e, event_id=ev,
                                              to_state=s, flags=_F_WILD)
                      for ev, s, e in (
                          (eid['DeathAnimation'], 1, rag_fx.ref),
                          (eid['Ragdoll'], 2, rag_fx.ref),
                          (eid['RagdollInstant'], 2, 'null'))),
            numelements=3)
        root_wild_ref = root_wild.ref

    root_sm = pf.add('hkbStateMachine')
    root_sm.param('variableBindingSet', 'null')
    root_sm.param('userData', 0)
    root_sm.param('name', f'{behavior_name}RootBehavior')
    root_sm.param_raw('eventToSendWhenStateOrTransitionChanges', (
        '<hkobject>\n\t<hkparam name="id">-1</hkparam>\n'
        '\t<hkparam name="payload">null</hkparam>\n</hkobject>'))
    root_sm.param('startStateChooser', 'null')
    root_sm.param('startStateId', 0)
    root_sm.param('returnToPreviousStateEventId', -1)
    root_sm.param('randomTransitionEventId', -1)
    root_sm.param('transitionToNextHigherStateEventId', -1)
    root_sm.param('transitionToNextLowerStateEventId', -1)
    root_sm.param('syncVariableIndex', -1)
    root_sm.param('wrapAroundStateId', False)
    root_sm.param('maxSimultaneousTransitions', 32)
    root_sm.param('startStateMode', 'START_STATE_MODE_DEFAULT')
    root_sm.param('selfTransitionMode', 'SELF_TRANSITION_MODE_NO_TRANSITION')
    root_sm.param_array('states', [s.ref for s in root_states])
    root_sm.param('wildcardTransitions', root_wild_ref)

    graph = pf.add('hkbBehaviorGraph')
    graph.param('variableBindingSet', 'null')
    graph.param('userData', 0)
    graph.param('name', f'{behavior_name}.hkb')
    graph.param('variableMode', 'VARIABLE_MODE_DISCARD_WHEN_INACTIVE')
    graph.param('rootGenerator', root_sm.ref)
    graph.param('data', gdata.ref)

    top = pf.add('hkRootLevelContainer')
    top.param_structs('namedVariants', [
        [('name', 'hkbBehaviorGraph'), ('className', 'hkbBehaviorGraph'),
         ('variant', graph.ref)]])
    return pf.render(top)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def _write_and_compile(xml: str, out_hkx: str):
    xml_path = out_hkx + '.xml'
    os.makedirs(os.path.dirname(os.path.abspath(out_hkx)), exist_ok=True)
    with open(xml_path, 'w', encoding='ascii', errors='replace',
              newline='\n') as f:
        f.write(xml)
    compile_hkx(xml_path, out_hkx)
    os.remove(xml_path)


def _apply_sound_slots(clip_meta: list, clips: dict, sound_slots: dict) -> int:
    """Turn a creature's CSDT sound slots into clip sound triggers.

    Oblivion keeps a creature's whole voice on the CREA record (idle, aware,
    attack, hit, death, footsteps) and its .kf files carry almost no sound text
    keys — exactly 1 of the goblin's 56, and that one is the bow string. Skyrim
    is the other way round: the actor record is nearly empty (36 CSDT entries
    across all 5118 vanilla NPC_, none of them Idle/Aware/Death) and the voice
    comes from `SoundPlay.<SNDR EditorID>` annotations in the animations. So
    the record data has to be replayed as annotations or the creature is
    silent.

    Only SINGLE-PLAY moments are handled here (attack swings, the death anim,
    plus footfall events on the gait cycle, which ARE per-cycle by nature).
    The Idle/Aware slots go through dedicated vocal states instead
    (generate_creature_project) — annotating the looping Idle/CombatStance
    clips fired them every cycle, in life and after death.

    A clip that already carries an authored sound key for a slot keeps it — the
    source is always the better authority when it exists.

    Returns the number of triggers added.
    """
    if not sound_slots:
        return 0
    from asset_convert.creature_pipeline import _CSDT_TO_CLIP

    by_name = {c['name']: c for c in clip_meta}

    def add(clip, t, edid):
        # The annotation MUST carry a descriptor name. Disassembly of the SSE
        # handler (0x140565c90, GOG build) settles it: after matching the
        # "SoundPlay" keyword it calls the string-length helper 0x140c60eb0 on
        # the payload and `je` straight to the exit when the length is ZERO —
        # a bare `SoundPlay:` is parsed, found empty, and dropped. Only on a
        # non-empty payload does it reach the lookup at 0x140c260f0, which
        # resolves the sound BY NAME. So `SoundPlay.<SNDR EditorID>` is the
        # only form that can ever produce audio; vanilla's bare `SoundPlay:`
        # entries are inert (they are leftovers from Bethesda's own pipeline).
        if any(abs(t0 - t) < 1e-3 and s0 == edid for t0, s0 in clip['sounds']):
            return 0
        clip['sounds'].append((t, edid))
        return 1

    added = 0
    for csdt, edid in sorted(sound_slots.items()):
        role = _CSDT_TO_CLIP.get(csdt)
        if role is None:
            continue
        kind, where = role
        if kind == 'death':
            c = by_name.get('Death')
            if c:
                added += add(c, 0.0, edid)
        elif kind == 'attacks':
            for c in clip_meta:
                if not c['name'].startswith('Attack_'):
                    continue
                # On the swing, not the wind-up: use the hit frame when the
                # source marked one, else a quarter into the clip.
                t = (max(0.0, min(c['hits']) - 0.2) if c.get('hits')
                     else c['duration'] * 0.25)
                added += add(c, t, edid)
        elif kind == 'locomotion' and where == 'foot':
            # Footfalls do NOT go through SoundPlay at all: vanilla creature
            # projects fire the engine's own footstep events (wolf 140/142
            # FootFront/FootBack, bear 56/59), which route through the race's
            # footstep set rather than a sound descriptor. The event name
            # must be EXACTLY a tag creature_footsteps put in FSTP.ANAM —
            # both derive from creature_pipeline.foot_tags. Clips with
            # authored 'Enum:' footfall keys keep them; the rest get two
            # contact points per cycle placed from the clip duration.
            from asset_convert.creature_pipeline import foot_tags
            tags = foot_tags(sound_slots)
            if not tags:
                continue
            if 'FootLeft' in tags:
                pair = [(0.25, 'FootLeft'), (0.75, 'FootRight')]
            else:
                pair = [(0.25, 'FootFront' if 'FootFront' in tags
                         else 'FootBack'), (0.75, 'FootBack')]
            for c in clip_meta:
                if not c['name'].startswith('Move') or c.get('feet'):
                    continue
                d = c['duration']
                if d <= 0:
                    continue
                c['feet'] = [(d * f, tag) for f, tag in pair]
                added += 2
    for c in clip_meta:
        c['sounds'].sort()
    return added


def generate_creature_project(creature_dir: str, name: str, out_root: str,
                              fps: float = 30.0, sound_slots: dict = None,
                              sound_chances: dict = None) -> dict:
    """Full project generation for one creature.

    Writes the hkx project tree plus `project_manifest.json` — the manifest
    is the contract consumed by asset_convert/animation_data.py (singlefile
    registration) and tes5_import (RACE ATKE/behavior-graph paths).

    sound_slots: {CSDT type: SOUN EditorID} for this creature's folder. Skyrim
    voices creatures through animation annotations rather than the actor
    record, so these become `SoundPlay.<SNDR>` clip triggers — see
    creature_pipeline._CSDT_TO_CLIP — except the Idle/Aware slots, which
    become dedicated single-play vocal states so they cannot fire per loop.
    sound_chances: {CSDT type: authored CSDC chance 0-100}, carried into the
    manifest's vocal_events for the import-side IDLE record conditions.
    """
    from asset_convert.creature_pipeline import foot_enum_map
    from asset_convert.hkx_anim import (decode_clip, event_annotations,
                                        parse_kf_events, write_clip_hkx)
    from asset_convert.hkx_ragdoll import ragdoll_info
    from asset_convert.hkx_skeleton import generate_skeleton_hkx

    skeleton_nif = os.path.join(creature_dir, 'skeleton.nif')
    lname = name.lower()
    proj_dir = os.path.join(out_root, 'actors', 'tes4', lname)
    clips = classify_clips(creature_dir)

    bones = generate_skeleton_hkx(
        skeleton_nif, os.path.join(proj_dir, 'character assets',
                                   'skeleton.hkx'))
    ragdoll = ragdoll_info(skeleton_nif, bones)

    # convert every clip the graph uses, collecting per-clip metadata
    # (the run gait clip is not a state — it feeds the MoveForward
    # parametric speed blend — but still needs conversion + registration)
    convert_list = list(state_defs(clips))
    if clips.get('run'):
        convert_list.append(('MoveForwardRun', clips['run'], True, None,
                             None))
    attack_kfs = set(clips['attacks'])
    enum_map = foot_enum_map(sound_slots)

    # Phase 1 — DECODE every clip and collect its translated events
    # (parse_kf_events: 'Sound: X' → SoundPlay descriptor names, authored
    # 'Enum: Left/...' footfalls → engine foot events, 'Hit' → hit times).
    # Compilation waits until _apply_sound_slots has folded the CREA CSDT
    # slots in, because the events must be EMBEDDED in the animation hkx as
    # annotations — the channel the engine dispatches at runtime (vanilla:
    # 58/74 wolf animations carry SoundPlay./FootFront/FootBack annotations
    # inside the .hkx; animationdata triggers alone stayed silent in game).
    decoded, decode_failed = {}, {}         # stem -> (clip, motion) / error
    clip_meta, motions, failures = [], {}, []
    for st_name, kf, looping, _enter, end_evt in convert_list:
        stem = _clip_state_name(kf)
        if stem not in decoded and stem not in decode_failed:
            try:
                decoded[stem] = decode_clip(kf, fps)
            except Exception as e:  # keep going; report at the end
                decode_failed[stem] = f'{type(e).__name__}: {e}'
        if stem in decode_failed:
            failures.append((kf, decode_failed[stem]))
            if st_name == 'MoveForwardRun':
                clips['run'] = None     # blender must not reference it
            continue
        clip, motion = decoded[stem]
        events = parse_kf_events(clip.text_keys, enum_map)
        if kf in attack_kfs and not events['hits']:
            # Keyless attack: the damage contract (weaponSwing/preHitFrame/
            # HitFrame, fired by the graph's clip triggers) still needs a hit
            # moment. ~40% in is where vanilla one-shot attacks put it.
            events['hits'] = [float(clip.duration) * 0.4]
        clip_meta.append({
            'name': st_name,
            'stem': stem,
            'anim': 'Animations\\' + stem + '.hkx',
            'duration': float(clip.duration),
            'looping': looping,
            'end_event': end_evt,
            # The SOUN EDID must survive: both the hkx annotation and the
            # animationdata trigger are 'SoundPlay.<SNDR EDID>' and the
            # engine resolves that name at playback.  Keeping only the
            # timestamp emitted a bare 'SoundPlay' naming no descriptor,
            # which plays nothing.
            # This channel is unrelated to plain NIF sequence text keys:
            # those stay in Oblivion's 'sound: X' form, which the engine
            # handles natively (nif_converter._convert_sound_text_keys).
            'sounds': events['sounds'],
            # Authored Oblivion footfall keys, already translated to the
            # engine's own footstep events (FSTP.ANAM match).
            'feet': events['feet'],
            # Oblivion 'Hit' text keys → HitFrame triggers (damage contract)
            'hits': events['hits'],
        })
        if motion and stem not in motions:
            motions[stem] = {
                'bone': motion['bone'],
                'duration': float(clip.duration),
                'times': motion['times'].tolist(),
                'translations': (motion['translations'].tolist()
                                 if motion['translations'] is not None
                                 else None),
                'rotations': (motion['rotations'].tolist()
                              if motion['rotations'] is not None else None),
            }

    # CREA CSDT sound slots → SoundPlay/footstep events on the right clips,
    # BEFORE compiling, so they land inside the animation hkx too.
    _apply_sound_slots(clip_meta, clips, sound_slots)

    # Vocal state for the CSDT Aware(5) slot. It CANNOT be an annotation on
    # the looping Idle/CombatStance clips — an annotation fires every loop
    # cycle, so the creature squeaked non-stop, and kept squeaking after
    # death because the ragdoll wrapper states loop the idle clip as their
    # pose source. Instead it is a single-play state playing its OWN copy of
    # the idle animation with the sound annotation, entered through the
    # engine's ActionIdleWarn IDLE record — the exact vanilla WolfIdleWarn
    # layout (leaf under the action, ENAM, aggroWarning lifecycle), and it
    # only ever fires during an aggro warning.
    #
    # The Idle(4) slot is DELIVERED NOWHERE for now — both candidate
    # channels are disqualified:
    #   * an annotation on the looping base idle fires every cycle (the
    #     confirmed squeak-spam bug; vanilla only does this for cow/goat
    #     cud-chewing — predators' mt_idle carries no SoundPlay at all);
    #   * an IDLE record under ActionIdle sent the actor into an
    #     engine-tracked dynamic idle over and over (authored chance 75+ per
    #     idle poll), and creatures stopped walking and floated in their
    #     idle — vanilla routes ActionIdle through deep per-creature
    #     NonCombatIdle chains whose lifecycle our minimal graph does not
    #     implement. Restoring idle chatter needs that full chain first.
    idle_stem = _clip_state_name(clips['idle']) if clips['idle'] else None
    vocal_states, vocal_events = [], []
    if idle_stem and idle_stem in decoded:
        idle_clip, _m = decoded[idle_stem]
        d = float(idle_clip.duration)
        edid = (sound_slots or {}).get(5)
        if edid:
            st_name, evt, stem = 'AwareVocal', 'awareVocalStart', 'awarevocal'
            decoded[stem] = decoded[idle_stem]
            clip_meta.append({
                'name': st_name, 'stem': stem,
                'anim': 'Animations\\' + stem + '.hkx',
                'duration': d, 'looping': False,
                'end_event': 'returnToDefault',
                'sounds': [(min(0.25, d * 0.25), edid)],
                'feet': [], 'hits': [],
            })
            vocal_states.append((st_name, evt, stem))
            vocal_events.append({
                'state': st_name, 'event': evt, 'slot': 5,
                'chance': (sound_chances or {}).get(5, 100),
            })
        # The ragdoll death state needs an annotation-free pose source (an
        # annotation in a looping corpse clip voices the corpse forever —
        # the squeaking-dead-rat bug), so 'ragdollpose' is a clean COPY of
        # the converted idle.  It must be the REAL converted clip, NOT a
        # synthesized frozen frame: the 2026-08-07 static_pose_clip
        # experiment shipped a hand-built 2-frame clip and the corpse
        # teleported on death (user-confirmed regression; the synthesized
        # root placement did not match the pipeline-converted clips).
        #
        # The clip_meta entry is REQUIRED, not bookkeeping: it is what
        # registers the 'FullyRagdollPose' clip generator in animationdata
        # and puts ragdollpose.hkx in the animationsetdata CRC preload list.
        # The engine binds creature clips exclusively through that cache —
        # every OTHER generator in the graph is registered (vanilla
        # registers its death/getup clips the same way: dogproject.txt
        # carries DeathPose, GetUpLeft, ...), and this one was not, so the
        # death state ran with a pose source that could never bind and the
        # entire ragdoll handoff died with it (2026-08-07 static-corpse /
        # sideways-teleport / misaligned-hitbox report).  No sounds/feet ->
        # its hkx annotation union stays empty, so corpses stay silent.
        if ragdoll:
            decoded['ragdollpose'] = (idle_clip, None)
            # rate 1.0 single-play, matching the graph clip (vanilla
            # death-clip semantics; the cache and graph playback speeds
            # must agree).  The `Ragdoll` event trigger is the release
            # into the limp ragdoll — see the pose_clip comment in
            # build_behavior_xml; it must be in BOTH the graph and here.
            clip_meta.append({
                'name': 'FullyRagdollPose', 'stem': 'ragdollpose',
                'anim': 'Animations\\ragdollpose.hkx', 'rate': 1.0,
                'duration': d, 'looping': False, 'end_event': None,
                'sounds': [], 'feet': [], 'hits': [],
                'events': [(_RAGDOLL_RELEASE_T, 'Ragdoll')],
            })

    # Phase 2 — COMPILE, embedding each animation FILE's full event union as
    # annotations (states sharing one file share its annotations; blend
    # children reuse base files, whose annotation times are file-local, so
    # only rate-1 entries contribute). Hits stay OUT of the annotations: the
    # graph already fires weaponSwing/preHitFrame/HitFrame through its
    # hkbClipTriggerArray and double-firing would double the damage window.
    # 'ragdollpose' has no clip_meta entry, so it compiles annotation-free.
    ann_by_stem = {}
    for c in clip_meta:
        ann = ann_by_stem.setdefault(c['stem'], set())
        ann.update(event_annotations(
            {'sounds': c['sounds'], 'feet': c.get('feet', [])},
            include_hits=False))
    for stem in sorted(decoded):
        clip, _motion = decoded[stem]
        out_hkx = os.path.join(proj_dir, 'animations', stem + '.hkx')
        try:
            write_clip_hkx(clip, bones, out_hkx,
                           sorted(ann_by_stem.get(stem, ())))
        except Exception as e:  # drop every state that used this file
            failures.append((stem + '.hkx', f'{type(e).__name__}: {e}'))
            dropped = {c['name'] for c in clip_meta if c['stem'] == stem}
            clip_meta = [c for c in clip_meta if c['stem'] != stem]
            motions.pop(stem, None)
            if 'MoveForwardRun' in dropped:
                clips['run'] = None

    # natural clip speeds (game units/sec) from root-motion endpoints —
    # ck-cmd calculateMOVTs: forwardWalk = |end translation| / duration.
    # These anchor both the MOVT SPED columns (tes5_import) and the
    # MoveForward parametric blend, so commanded speed == animation speed.
    def _speed_of(kf_path):
        if not kf_path:
            return None
        m = motions.get(_clip_state_name(kf_path))
        if not m or not m['translations'] or not m['duration']:
            return None
        end = m['translations'][-1]
        v = (end[0] ** 2 + end[1] ** 2) ** 0.5 / m['duration']
        return round(v, 3) if v > 1.0 else None

    speeds = {
        'walk': _speed_of(clips['locomotion'].get('MoveForward')),
        'run': _speed_of(clips.get('run')),
        'back': _speed_of(clips['locomotion'].get('MoveBackward')),
        'swim': _speed_of(clips['locomotion'].get('Swim')),
    }
    # a "run" clip that isn't actually faster than the walk (wraith:
    # runforward has LESS root motion than forward) breaks the parametric
    # blend's increasing-anchor contract and the MOVT columns — treat the
    # run gait as absent (MOVT run falls back to walk).
    if (speeds['run'] and speeds['walk']
            and speeds['run'] <= speeds['walk'] * 1.05):
        speeds['run'] = None
        clips['run'] = None

    # register the parametric-blend children (same clips at scaled
    # playbackSpeeds — see speed_blend_plan) in the animationdata cache:
    # every hkbClipGenerator name in the graph needs a cache entry with its
    # playback rate, trigger times in playback-local time (vanilla
    # dogproject.txt convention).
    base_of = {c['name']: c for c in clip_meta}
    for plan in (speed_blend_plan(clips, speeds) or [],
                 backward_blend_plan(clips, speeds) or []):
        for cnm, kf, rate, _anchor in plan:
            if cnm in base_of:
                continue
            stem = _clip_state_name(kf)
            base = next((c for c in clip_meta if c['stem'] == stem
                         and c.get('rate', 1) == 1), None)
            if base is None:
                continue
            entry = {
                'name': cnm, 'stem': stem, 'anim': base['anim'],
                'duration': base['duration'], 'looping': True,
                'end_event': None, 'rate': rate,
                'sounds': [(t / rate, s) for t, s in base['sounds']],
                'feet': [(t / rate, n) for t, n in base.get('feet', [])],
                'hits': [],
            }
            clip_meta.append(entry)
            base_of[cnm] = entry

    behavior_name = f'TES4{name.capitalize()}Behavior'
    move_types = movement_type_names(lname)
    # The graph must declare every qualified sound event its clips trigger,
    # exactly as animation_data.project_block_lines writes it — the engine
    # dispatches annotations through this table by name.
    sound_events = sorted({f'SoundPlay.TES4_{edid}_SNDR'
                           for c in clip_meta
                           for _t, edid in c.get('sounds', []) if edid})
    # A vocal state whose animation failed to compile must not reach the
    # graph (its clip would reference a missing file).
    surviving = {c['name'] for c in clip_meta}
    vocal_states = [v for v in vocal_states if v[0] in surviving]
    vocal_events = [v for v in vocal_events if v['state'] in surviving]
    _write_and_compile(
        build_behavior_xml(behavior_name, clips,
                           hit_times={c['name']: c['hits']
                                      for c in clip_meta if c['hits']},
                           movement_types=move_types,
                           speeds=speeds, ragdoll=ragdoll,
                           sound_events=sound_events,
                           vocal_states=vocal_states),
        os.path.join(proj_dir, 'behaviors', behavior_name.lower() + '.hkx'))
    # dedupe: states can share one animation file (Idle + CombatStance);
    # ragdollpose.hkx arrives through its FullyRagdollPose clip_meta entry
    anim_files = list(dict.fromkeys(c['anim'] for c in clip_meta))
    _write_and_compile(
        build_character_xml(
            f'TES4{name.capitalize()}Character', anim_files,
            f'Behaviors\\{behavior_name.lower()}.hkx', n_bones=len(bones)),
        os.path.join(proj_dir, 'characters', f'tes4{lname}character.hkx'))
    _write_and_compile(
        build_project_xml(f'Characters\\tes4{lname}character.hkx'),
        os.path.join(proj_dir, f'tes4{lname}project.hkx'))

    attack_states = [(evt, f'Attack_{_clip_state_name(kf)}')
                     for kf, evt in zip(clips['attacks'],
                                        build_attack_events(clips))]
    converted = {c['name'] for c in clip_meta}
    manifest = {
        'name': lname,
        'project_hkx': f'Actors\\TES4\\{lname}\\tes4{lname}project.hkx',
        'project_txt': f'tes4{lname}project.txt',
        'project_files': [f'Behaviors\\{behavior_name.lower()}.hkx',
                          f'Characters\\tes4{lname}character.hkx',
                          'Character Assets\\skeleton.HKX'],
        'anim_dir': f'meshes\\actors\\tes4\\{lname}\\animations',
        'clips': clip_meta,
        'attacks': [[e, s] for e, s in attack_states if s in converted],
        'movement_types': move_types,
        'speeds': speeds,
        'has_ragdoll': bool(ragdoll),
        # ragdoll part bone names -> the race's generated BPTD (body part
        # data); node names must exist in THIS skeleton or the engine's
        # ragdoll/hit binding has nothing to attach to
        'ragdoll_bones': (ragdoll or {}).get('part_bones', []),
        # Vocal idle states: tes5_import/creature_idles generates the
        # ActionIdle/ActionIdleWarn IDLE records that let the engine enter
        # them (event = the IDLE's ENAM; chance = authored TES4 CSDC).
        'vocal_events': vocal_events,
        'motions': motions,
        'bones': len(bones),
        'failures': failures,
    }
    with open(os.path.join(proj_dir, 'project_manifest.json'), 'w',
              encoding='utf-8') as f:
        json.dump(manifest, f)
    return manifest


if __name__ == '__main__':
    import argparse
    ap = argparse.ArgumentParser(
        description='Generate a full Skyrim LE behavior project from an '
                    'Oblivion creature folder')
    ap.add_argument('creature_dir')
    ap.add_argument('out_root')
    ap.add_argument('--name', help='creature name (default: folder name)')
    ap.add_argument('--fps', type=float, default=30.0)
    args = ap.parse_args()

    name = args.name or os.path.basename(os.path.normpath(args.creature_dir))
    manifest = generate_creature_project(args.creature_dir, name,
                                         args.out_root, fps=args.fps)
    print(f"project: {manifest['project_hkx']}")
    print(f"bones: {manifest['bones']}, "
          f"animations: {len(manifest['clips'])}")
    for evt, state in manifest['attacks']:
        print('  attack event:', evt, '->', state)
    for kf, err in manifest['failures']:
        print('  FAILED:', os.path.basename(kf), err)
